### ISSUE TITLE
DiffObservableList doesn't work well with the items that extend BaseObservable

### ISSUE THREAD

**Issue by kmalmur** [evant/binding-collection-adapter#101]
The case is the following:
- my `DiffObservableList` contains item view models that extend `BaseObservable` so that the items can be updated without updating the list (which is much heavier than finding an appropriate item in the `DiffObservableList` and updating a text on it)
- everything works fine, assuming that I'll not call the `DiffObservableList.update` method with unmodified items. The `diffUtil` will not find any changes but the `DiffObservableList` will update the internal list. The new items are not bound to the view so calling `notifyPropertyChanged` doesn't have any effect. 

I think the solution is to get rid of list update for items that did not change.

**Comment by GSala** [comment]
I ran into the same issue. When I update the list with new Items, if the items haven't changed, the `DiffObservableList` hold the references to the new items, but since `notifyItemChanged` is not called, the new object is not bound to the layout because the adapter does not call `bindView`. When this happens, if the items bound to the layout are mutable, its changes are not reflected in the view.

Is there any work being done on this?

**Comment by evant** [comment]
Maybe you can give an example of what you are trying to do? Using mutable items with diff util doesn't sound right.

**Comment by GSala** [comment]
In my case, the items in my recyclerView need to fetch some data remotely. To do that I need to relay some lifecycle events to them so they can initiate network calls and clear resources. The purpose of DiffUtil would be to know about the position of these items, for example.

So when I update the list with a new list of items, if the items haven't changed, the new items don't get bound but the DiffObservableList contains the new items. When I call the lifecycle on the items of the DiffObservableList, they start network requests and mutate, but nothing is reflected in the view.

What would you do with this use case?

**Comment by evant** [comment]
Hm, I think I understand what's going on now, though I'm not sure how to solve this efficiently. Seems like it would need to rebind all items from the new list for it to work correctly.

**Comment by GSala** [comment]
I also think that binding all the items defeats the purpose of the diff. It would also trigger change animations and so on.  

Maybe a possible solution would be to only replace the items that have changed, in the collection. Using the diff result maybe. For example, if the `DiffObservableList` contains `[1,2,3,4]` and I update with `[1,2,6,7]`, if the list maintains the reference to the old `1` and `2`, since these are already bound to the views, I could mutate these. I haven't completely thought about the implications of such a change. 

What do you think?

**Comment by evant** [comment]
Maybe, would also have to handle insertions and deletions too.

**Comment by kmalmur** [comment]
Is there any work being done on this?

**Comment by theunderdoge** [comment]
Recently faced the same issue. My workaround is to get hash code from list with new items and compare it with hash code from old item's list. If hash codes are not equal, DiffObservableList should be updated.

**Comment by evant** [comment]
So I'm not really convinced that mixing mutable and immutable changes like this is a good idea. Either you should go down the mutable route and use `ObservableArrayList` and change things to match your data. Or you go the immutable route and submit a new list each time.
