### ISSUE TITLE
ObservableArrayList to LiveData

### ISSUE THREAD

**Issue by ersin-ertan** [evant/binding-collection-adapter#130]
https://developer.android.com/topic/libraries/data-binding/architecture#livedata

> LiveData objects know about the lifecycle of the observers subscribed to the data changes

> replace observable fields with LiveData

I've been testing the recycler view beta, and the use of ObservableArrayList was a bit odd because the android docs recommend moving away from observable fields. Would it be a natural evolution for the recycler view implementation and diffing/merging to use LiveData instead?

**Comment by evant** [comment]
I assume you mean something like exposing a `LiveData<List>` and using diffutil for the updates? You can do this using `DifObservableList` like so:

```java
DiffObservableList<Foo> diffList = new DiffObservableList<>(diffCallback);
adapter.setItems(diffList);
liveDataList.observe(this, diffList::update);
```

I'm considering updating it's implementation to be based on `AsyncListDiffer` to make running the diff on a background thread easier. Might be also got to have some utility to make the above setup simpler.

**Comment by evant** [comment]
Started work on it https://github.com/evant/binding-collection-adapter/tree/better-diff-support. Added a new `AsyncDiffObservableList` based on `AsyncListDiffer`. Additionally, you can bind your `DiffUtil.ItemCallback` to the recyclerview and it'll automatically use it.

```xml
<androidx.recyclerview.widget.RecyclerView
    android:id="@+id/list"
    app:diff="@{itemCallback}"
    app:itemBinding="@{itemBinding}"
    app:items="@{list}"
    app:layoutManager="androidx.recyclerview.widget.LinearLayoutManager" />
```
(list can be `LiveData<List<Foo>>`) and things will work like you'd expect.

The old `DiffObservableList` is still around, though not sure it's worth keeping? This will likely land in `3.0.0` so breaking changes are _ok_.

**Comment by chpasha** [comment]
I think, that the current behavior with binding to LiveData is not optimal. Why? Because you bind to List<T>, not to LiveData<List<T>>  - so when LiveData content changes, no UI updates happen. We can workaround the issue by implementing Observable in ViewModel and issuing notifyPropertyChanged every time the LiveData changes - that will cause DataBinding to rebind a new List, but that defeats the purpose of using LiveData, since we have to explicitly notify about its change . Besides that - there is an even bigger problem with it - if we bind to result of Transformations - those fields won't be ever triggered unless there is an observer to them - and there is no one, since we bind not to LiveData but to it's content.

So the optimal behaviour might be to accept LiveData as data source in BindingAdapter and observe it there, but I guess the problem is that you cannot get a LifecycleOwner from the View, am I right?

**Comment by chpasha** [comment]
P. S. what about creating custom lifecycleowner. I have written a small prove-of-concept BindingAdapter that proxies your adapter and subscribes to LiveData changes. Seems to work as expected and observes seem to be added and removed correctly when leaving and entering fragment again. 

```
public class ViewLifecycleOwner implements LifecycleOwner, View.OnAttachStateChangeListener {

    private LifecycleRegistry registry = new LifecycleRegistry(this);

    private final View view;

    public ViewLifecycleOwner(View view) {
        this.view = view;
        view.addOnAttachStateChangeListener(this);
        //set STARTED here since onViewAttachedToWindow is not called if fragment is re-attached from detached state
        registry.setCurrentState(Lifecycle.State.STARTED);
    }

    @NonNull
    @Override
    public Lifecycle getLifecycle() {
        return registry;
    }

    @Override
    public void onViewAttachedToWindow(View v) {
        
    }

    @Override
    public void onViewDetachedFromWindow(View v) {
        view.removeOnAttachStateChangeListener(this);
        registry.setCurrentState(Lifecycle.State.DESTROYED);
    }
}
```

and then in binding adapter 

```
public class CustomDataBindingAdapters {
    @BindingAdapter(value = {"itemBinding_", "items_", "itemsLive_", "adapter_", "itemIds_", "viewHolder_", "diffConfig_"}, requireAll = false)
    public static <T> void setAdapter(RecyclerView recyclerView,
                                      ItemBinding<T> itemBinding,
                                      List<T> items,
                                      LiveData<List<T>> itemsLive,
                                      BindingRecyclerViewAdapter<T> adapter,
                                      BindingRecyclerViewAdapter.ItemIds<? super T> itemIds,
                                      BindingRecyclerViewAdapter.ViewHolderFactory viewHolderFactory,
                                      AsyncDifferConfig<T> diffConfig) {
        if (itemsLive != null) {
            itemsLive.observe(new ViewLifecycleOwner(recyclerView), list -> {
                setAdapter(recyclerView, itemBinding, list, adapter, itemIds, viewHolderFactory, diffConfig);
            });
        } else {
			setAdapter(recyclerView, itemBinding, items, adapter, itemIds, viewHolderFactory, diffConfig);
        }
    }

    private static <T> void setAdapter(RecyclerView recyclerView, ItemBinding<T> itemBinding, List<T> list, BindingRecyclerViewAdapter<T> adapter, BindingRecyclerViewAdapter.ItemIds<? super T> itemIds, BindingRecyclerViewAdapter.ViewHolderFactory viewHolderFactory, AsyncDifferConfig<T> diffConfig) {
        BindingRecyclerViewAdapters.setAdapter(recyclerView, itemBinding, list, adapter, itemIds, viewHolderFactory, diffConfig);
    }
}
```

the drawback here is that we have to introduce a new attribute for livedata, since List always takes precedence. But the profit here is that livedata will work as expected via observe, we don't have to notify about property changes manually and transformation fields will work as well when bound. What do you think?

**Comment by chpasha** [comment]
Let's say, we have a ViewModel, that looks like this (I skip getters for brevity)
```
public class MainModel extends ViewModel
{
	private MutableLiveData<List<String>> items = new MutableLiveData<>();

	private LiveData<List<String>> itemsTransformed = Transformations.switchMap(otherItems, this::toItems);

       private MutableLiveData<List<String>> toItems(List<String> source) {
		Collections.reverse(source);
		return new MutableLiveData<>(source);
	}

	public void loadData()
	{
		otherItems.setValue(asList("1", "2", "3"));		
	}

}
```

if we bind our RecyclerView via 

```
 <androidx.recyclerview.widget.RecyclerView
            android:id="@+id/list"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            app:layoutManager="LinearLayoutManager"

            app:itemBinding="@{model.itemBinding}"
            app:items="@{model.items}"
            />
```

and call model.loadData() after that in Fragment, the UI won't change because Android Data Binding generates code like this

```
java.util.List<String> modelItemsGetValue = modelItems.getValue();
BindingRecyclerViewAdapters.setAdapter(this.list, BindingCollectionAdapters.toItemBinding(modelItemBinding), modelItemsGetValue, ....)
```
as you can see, we bind to the content of the items, not to the LiveData-Object, so if it's content changed, the new content won't be bound via BindingRecyclerViewAdapters.setAdapter
This **can be worked around** if we declare our model as implements Observable, and notify Data Binding about property change manually (somewhere after setValue) - then it will **rebind** to the new content by triggering executeBindings again, so the code above will run again, but this time MutableLiveData.getValue will contain new values. This manual notification ruins the idea of LiveData notifying observers automatically. Because we don't subscribe to it in BindingAdapter

And then we have transformations case: if we bind RecyclerView to itemsTransformed - it will never receive the new content even if we notify about changes. Because Transformations.switchMap creates MediatorLiveData that is **never triggered** if nobody subscribes to it. As workaround we have to observe the variable in our Fragment like itemsTransformed.observe() and only after that the content would be populated since there will be one subscriber. 

So if we could pass LiveData instead of List to the BindingAdapter and observe it there, it would solve both issues. Is it more clear to you now?

**Comment by chpasha** [comment]
P. S. I've took BindingRecyclerViewAdapters from master and modified it. Maybe you understand better what I mean if you look at my changes

```
public class BindingRecyclerViewAdapters {

    @BindingAdapter(value = {"itemBinding", "items", "itemsLive", "adapter", "itemIds", "viewHolder", "diffConfig"}, requireAll = false)
    public static <T> void setAdapter(RecyclerView recyclerView,
                                      ItemBinding<? super T> itemBinding,
                                      List<T> items,
								      LiveData<List<T>> itemsLive,
                                      BindingRecyclerViewAdapter<T> adapter,
                                      BindingRecyclerViewAdapter.ItemIds<? super T> itemIds,
                                      BindingRecyclerViewAdapter.ViewHolderFactory viewHolderFactory,
                                      AsyncDifferConfig<T> diffConfig) {

    	if (itemsLive != null) {
			itemsLive.observe(new ViewLifecycleOwner(recyclerView), list ->
				setAdapter(recyclerView, itemBinding, list, adapter, itemIds,
						   viewHolderFactory, diffConfig));
		} else {
			setAdapter(recyclerView, itemBinding, items, adapter, itemIds, viewHolderFactory, diffConfig);
		}
	}

	private static <T> void setAdapter(RecyclerView recyclerView, ItemBinding<? super T> itemBinding, List<T> items, BindingRecyclerViewAdapter<T> adapter,
		BindingRecyclerViewAdapter.ItemIds<? super T> itemIds, BindingRecyclerViewAdapter.ViewHolderFactory viewHolderFactory, AsyncDifferConfig<T> diffConfig)
	{
		if (itemBinding == null) {
			throw new IllegalArgumentException("itemBinding must not be null");
		}
		BindingRecyclerViewAdapter oldAdapter = (BindingRecyclerViewAdapter) recyclerView.getAdapter();
		if (adapter == null) {
			if (oldAdapter == null) {
				adapter = new BindingRecyclerViewAdapter<>();
			} else {
				adapter = oldAdapter;
			}
		}
		adapter.setItemBinding(itemBinding);

		if (diffConfig != null && items != null) {
			AsyncDiffObservableList<T> list = (AsyncDiffObservableList<T>) recyclerView.getTag(R.id.bindingcollectiondapter_list_id);
			if (list == null) {
				list = new AsyncDiffObservableList<>(diffConfig);
				recyclerView.setTag(R.id.bindingcollectiondapter_list_id, list);
				adapter.setItems(list);
			}
			list.update(items);
		} else {
			adapter.setItems(items);
		}

		adapter.setItemIds(itemIds);
		adapter.setViewHolderFactory(viewHolderFactory);

		if (oldAdapter != adapter) {
			recyclerView.setAdapter(adapter);
		}
	}

	@BindingConversion
    public static <T> AsyncDifferConfig<T> toAsyncDifferConfig(DiffUtil.ItemCallback<T> callback) {
        return new AsyncDifferConfig.Builder<>(callback).build();
    }
}
```
so, I added another attribute, itemsLive and if it is not null, I observe it for changes, and every time it triggers new data, I rebind the adapter. If it is null, everything goes as usual. So now, the LiveData behaves exactly the same as ObservableList would do - it notifies about changes without any manual work. The code for ViewLifecylceOwner I've shown above and this is the only place where I'm not sure if there are 100% no leaks. It would be perfect if the view had getLifefycleOwner-Method but well, it doesn't :(

**Comment by evant** [comment]
So I would expect databinding to update not because the adapter is observing live data, but because you are binding a live data in xml and it'll re-trigger setAdapter. If that's not working that's surprising. Let me play around with this.

**Comment by evant** [comment]
Note: the sample app is using LiveData https://github.com/evant/binding-collection-adapter/blob/master/app/src/main/java/me/tatarka/bindingcollectionadapter/sample/ImmutableViewModel.kt

**Comment by evant** [comment]
You said to omitted the getter for brevity, bit it's `LiveData<List<String>> getItems()` correct?

**Comment by chpasha** [comment]
Yes, actually MutableLiveData<List<String>> since I use lombok Getter. And you're right, the Data Binding should be triggering onFieldChange for items - it does generate code for the field. But somehow it is not triggered when LiveData content changes. I'm investigating now if it has something to do with the fact, that my RecyclerView is added and bound from ViewStub.

**Comment by chpasha** [comment]
Yes, it has something to do with ViewStub-Binding. if I put recyclerview directly in fragment, the field change triggers rebinding - but if it is bound in runtime when viewstub is inflated, changes are not propagated. That explains why I'm the only one experiencing the issue :-D .

**Comment by chpasha** [comment]
I found the problem: if you bind a model in ViewStub like this
```
 <ViewStub android:id="@+id/list"
                  android:layout_width="match_parent"
                  android:layout_height="match_parent"

                  app:model="@{model}"/>
```
and then bind items and itemsBinding in layout inflated instead of the ViewStub - then changes for the fields are not triggered, only changes for the model itself. The workaround is to bind to model fields like this

```
<ViewStub android:id="@+id/list"
                  android:layout_width="match_parent"
                  android:layout_height="match_parent"

                  app:items="@{model.items}"
                  app:itemBinding="@{model.itemBinding}"/>
```
unfortunately that doesn't make much sense to me, since I want to bind to model to be able to name the concrete fields as I want and not always have items and itemBinding. So maybe I still need a custom solution like subscription to LiveData in Adapter if I don't find any legal way to make those fields in ViewStub-Binding trigger.
Sorry for disturbing you, since it is not an BindingAdapter-Issue at first place

**Comment by evant** [comment]
> that my RecyclerView is added and bound from ViewStub.
That's very possible, you might need to call `setLifecycleOwner` on the adapter manually.

**Comment by chpasha** [comment]
I'll try, but I don't think it will work - as far as I can see - it sets Lifecycle-Owner for every item view inside recyclerview, but my problem is that RecyclerView itself is not re-populated with new data when LiveData-Changes, have to find out, where onFieldChange of ViewBinding is triggered from and why it doesn't work for ViewStub

**Comment by chpasha** [comment]
Holy cow. It was LifecycleOwner, but not of the adapter, but of the ViewStub itself. You have to set the lifecycle-owner on it when it is inflated

```
viewStubProxy.setOnInflateListener((stub, view) ->
            {
                viewStubBinding = DataBindingUtil.bind(view);
                viewStubBinding.setLifecycleOwner(this);
            });
```

after that, Observers on LiveData fields will be setup properly and all field changes are triggered as they should. Shame on me :(

**Comment by evant** [comment]
Ah yeah. Feel free to star https://issuetracker.google.com/issues/112929938 for providing a method to not have to set the lifecycle owner manually.

**Comment by evant** [comment]
It wouldn't be enough no, view's `onViewDetachedFromWindow()` doesn't get called when the parent Fragment/Activity is destroy so you'd still need to obtain the parent lifecycle somehow.
