### ISSUE TITLE
Support for FragmentPagerAdapter with ViewPager

### ISSUE THREAD

**Issue by Jaypeg85** [evant/binding-collection-adapter#15]
Hi,

It would be great if you could bind a collection of viewmodels for fragments to a ViewPager, so that each page had it's own lifecycle.

**Comment by evant** [comment]
I'll have to think about this, but my first impression is that this doesn't fit well with the scope of this library. This library provides two features: binding item layouts to a collection view, and automatically notifying the collection view on updates. With fragments, you need neither of these as the fragment itself provides the layout, and you almost always just have a static collection of fragments to display in a pager. If you really want to use binding here it's pretty trivial to implement it yourself

```java
@BindingAdapter("fragments")
public void setFragments(ViewPager viewPager, final List<? extends Fragment> fragments) {
    viewPager.setAdapter(new FragmentPagerAdapter() {
        @Override
        public Fragment getItem(int position) {
            return fragments.get(position);
        }

        @Override
        public int getCount() {
            return fragments.size();
        }
    });
}
```

**Comment by Jaypeg85** [comment]
I see your point and I agree.

**Comment by bj0** [comment]
I have a question on this topic.  I understand the reasoning about the typical fragment use-case being out of the scope of this library, but I have a use-case this is sort of a hybrid between the two.

I have a dynamic collection of similar items (ideally represented by a collection of viewmodels) that I display in a ViewPager (each item has a corresponding 'screen').  I use fragments because each 'screen' has a TextureView, and I need to use the lifecycle events to get the view and know when I can draw to it (when it's on-screen).

This is basically item layouts + collection view + lifecycle events.  It's more like this library's use-case than it is like the traditional ```FragementPagerAdapter``` use-case.  So much so, that I had to re-write ```FragmentPagerAdapter``` because it cannot handle removing/adding fragments dynamically.  This leaves me with a big ugly custom adapter to maintain that could be completely eliminated with an observable collection.

**Comment by evant** [comment]
If you just need lifecycle events, you can actually obtain those in a custom view by using `ActivityLifecycleCallbacks`. Register a listener in `onAttachToWindow()` and unregister in `onDetachFromWindow()`. Then in the callbacks check to see if the passed activity equals your context and if so do your work. I've implemented this in a project recently and it works pretty well.
