### ISSUE TITLE
Support for onItemClicked event

### ISSUE THREAD

**Issue by slavik57** [evant/binding-collection-adapter#46]
It would be nice if you could add an attribute for a method to invoke with the item that was clicked

**Comment by evant** [comment]
You mean for listview? You can already do this with something like:
```xml
<ListView
  ...
  android:onItemClickListener="@{viewModel::onItemClick}" />
```

Recyclerview doesn't have this method because it doesn't scale to multiple click targets on an item. I usually handle this by adding click handler(s) to the items in the list and binding in the item layout. https://github.com/evant/binding-collection-adapter/issues/40 might be a solution if you want a single shared listener for all the items, though it hasn't been implemented yet.

**Comment by slavik57** [comment]
What I ment was a listener that would take parameter of the item time and not the view type. If I have a list of strings then the click listener would receive a string as a parameter

**Comment by evant** [comment]
You can get the item from that callback
```java
public void onItemClick(AdapterView<?> parent, View view, int position, long id) {
   ViewModel item = ((BindingCollectionAdapter<ViewModel>) parent.getAdapter()).getAdapterItem(position);
}
```
Feel free to create your own `@BindingAdapter` that does this for you. I'm not convinced this needs to be directly supported in this lib proper.

**Comment by evant** [comment]
This should be solvable by either the above or attaching your own item listener in 2.0.
