### ISSUE TITLE
LayoutManager from binding is not restoring position

### ISSUE THREAD

**Issue by stepansanda** [evant/binding-collection-adapter#59]
Hi, I'm using this library and I set the `LayoutManager` with binding like this `app:layoutManager="@{LayoutManagers.linear()}"`
Unfortunately, when I rotate the screen, or if I re-attach the Fragment again, the new `LayoutManager` is created, and the `RecyclerView` is scrolled on top. 

If I set the `LayoutManager` from the code (in `Fragment` in `onActivityCreated` method), the RecyclerView has the same position after rotation or after re-attaching.

Did I miss something? Do you have any suggestion how to handle this?

Otherwise I'm really enjoying this library!

**Comment by sevar83** [comment]
I think what causes the problem is the proper moment when you perform the binding. I suppose LM must be set earlier than the call to `Fragment.onViewStateRestored()` or `Activity.onRestoreInstanceState()` (if you use activity not a fragment). You could put a breakpoint on one of those to see if a layout manager is already bound to recyclerview at that moment. In any case you could make the binding happen right now with `YourBinding.executePendingBindings()`. 
I wrote a binding adapter for setting the most important parameters of a layout manager. It also does the transfer of the state when switching between different LM's. https://github.com/evant/binding-collection-adapter/issues
